version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env.production
    volumes:
      - ./storage:/app/storage
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    environment:
      - VITE_API_BASE=${VITE_API_BASE}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  # Optional: PostgreSQL database
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=mapping_tool
      - POSTGRES_USER=mapping_user
      - POSTGRES_PASSWORD=secure_password_here
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
