version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
    dockerfile: frontend/Dockerfile
    environment:
      - VITE_API_BASE=http://localhost:8000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
